### PR TITLE
Update goreleaser to 1.17.2

### PR DESCRIPTION
**Pull request by didil**
Part of https://github.com/jsdelivr/globalping-cli/issues/49

- built and installed .deb file on Debian 11 without any issues
- build and installed .rpm file on CentOS Linux release 7.9.2009 without any issues

### CODE REVIEW

**Comment by jimaek** [comment]
If the broken 1.17 version works then lets update to latest [v1.19.2](https://github.com/goreleaser/goreleaser/releases/tag/v1.19.2)

Can you test it?

**Comment by didil** [comment]
@jimaek I would suggest we first merge / do the full release on master to make sure it all works ? I can't really test the entire github action manually

**Comment by jimaek** [comment]
The action itself works fine, at least 1.17 for sure. If you tested the debs then its fine. I would suggest you test the deb and rpm packages generated by 1.19.2 and if they also work we merge the 1.19.2. 

But we also have no changes to release, so even if we merged there is no way to test anything

**Comment by didil** [comment]
@jimaek just tested, both dev and rpm packages working with 1.19.2

**Pull request merged**
